### ISSUE TITLE
Design feedback

### ISSUE THREAD

**Issue by gregjd** [govex/datastandards.directory#9]
Overall, I'm very excited for this site! Awesome work so far! 😄 A few (hopefully constructive!) comments about the design:

### The two-column section ("What are Open Data Standards?" and "How are Open Data Standards Useful?")

- Feels very wide. The text almost touches the edge of the screen. I'd suggest constraining the width to be the same as the content above.
- The text in that section is justified. I'd [strongly suggest](https://designforhackers.com/blog/justify-text-html-css/) left-aligning it.
- Because the question header on the right column ("How are Open Data Standards Useful?") spills onto a second line, the paragraph below that versus the paragraph for the left column start at different vertical points. It would look better if both paragraphs started at the same place vertically. But, it would be weird if that were accomplished by having a huge amount of space under the question header on the left. Probably the easiest way to do this is to shorten the question on the right to something like "How are standards useful?" Alternatively, you could ditch the two-column layout and just have the questions one after another — which would especially make sense given that the second question kind of depends on the first.

### Glossary and About pages

- The text coloring is a bit jarring. The black text on dark-green background is a little hard to read, and it's a huge contrast from the white hyperlinks.
- Same comment re: justified text as above.

### Category search results

- On the web, "search results" pages almost always serve as lists of links to click on. So it's confusing for this page to say something like "Search results for: Real-Time Transit" but then when you go to click on a standard's title it's not actually a hyperlink (and for that matter, there doesn't seem to be any link to a separate page on this website at all, only external links). This problem is amplified by the fact that the box for each standard has a shadow around it — a design feature that strongly implies clickability.

**Comment by Noznoc** [comment]
Hi,

I apologize for the delay. 

Thank you for your constructive feedback! As I am new to web development and design, most feedback is constructive, so feel free to provide more as the site develops and expands. I will adapt some of your design suggestions into the site ASAP. 

Best,
Julia
